@echo off
wmic os get BootDevice
wmic os get BuildNumber
wmic os get BuildType
wmic os get Caption
wmic os get CodeSet
wmic os get CountryCode
wmic os get CreationClassName
wmic os get CSCreationClassName
wmic os get CSDVersion
wmic os get CSName
wmic os get CurrentTimeZone
wmic os get DataExecutionPrevention_Available
wmic os get DataExecutionPrevention_32BitApplications
wmic os get DataExecutionPrevention_Drivers
wmic os get DataExecutionPrevention_SupportPolicy
wmic os get Debug
wmic os get Description
wmic os get Distributed
wmic os get EncryptionLevel
wmic os get ForegroundApplicationBoost = 2
wmic os get FreePhysicalMemory
wmic os get FreeSpaceInPagingFiles
wmic os get FreeVirtualMemory
wmic os get InstallDate
wmic os get LargeSystemCache
wmic os get LastBootUpTime
wmic os get Locale
wmic os get Manufacturer
wmic os get MaxNumberOfProcesses
wmic os get MaxProcessMemorySize
wmic os get Name
wmic os get NumberOfLicensedUsers
wmic os get NumberOfProcesses
wmic os get NumberOfUsers
wmic os get OperatingSystemSKU
wmic os get Organization
wmic os get OSArchitecture
wmic os get OSLanguage
wmic os get OSProductSuite
wmic os get OSType
wmic os get OtherTypeDescription
wmic os get PAEEnabled
wmic os get PlusProductID
wmic os get PlusVersionNumber
wmic os get PortableOperatingSystem
wmic os get Primary
wmic os get ProductType
wmic os get RegisteredUser
wmic os get SerialNumber
wmic os get ServicePackMajorVersion
wmic os get ServicePackMinorVersion
wmic os get SizeStoredInPagingFiles
wmic os get Status
wmic os get SuiteMask
wmic os get SystemDevice
wmic os get SystemDirectory
wmic os get SystemDrive
wmic os get TotalSwapSpaceSize
wmic os get TotalVirtualMemorySize
wmic os get TotalVisibleMemorySize
wmic os get Version
wmic os get WindowsDirectory
pause
@echo on